# Data Overview
Mario Castro

In [1]:
import pandas as pd

In [2]:
path = r"../Data/raw"

df_info = pd.read_csv(f"{path}/INFO_AUG.csv")
df_quest = pd.read_csv(f"{path}/QUEST_AUG.csv")
df_reflex = pd.read_csv(f"{path}/REFLEX_AUG.csv")

## Info dataframe:

In [3]:
df_info.head()

,client_utterance,clinician_utterance,behavior_code_1
0,He estado usando los ejercicios de respiración...,Estudios muestran que el 65% de los veteranos ...,GI
1,He estado usando los ejercicios de respiración...,Como ya has experimentado un avance en tu cont...,PE
2,"He intentado dejar de fumar varias veces, pero...",La nicotina en el cuerpo se reduce a la mitad ...,GI
3,"He intentado dejar de fumar varias veces, pero...",Tu fuerza en el servicio puede aplicarse ahora...,PE
4,"Sé que fumo demasiado, pero me ayuda a relajar...",El uso crónico de marihuana puede alterar la m...,GI

In [4]:
df_info.shape

(200, 3)

In [5]:
df_info['behavior_code_1'].value_counts()

behavior_code_1
GI    100
PE    100
Name: count, dtype: int64

## Quest dataframe:

In [6]:
df_quest.head()

,client_utterance,clinician_utterance,behavior_code_1
0,He estado practicando técnicas de respiración ...,¿Qué técnicas de respiración has encontrado má...,OQ
1,He estado practicando técnicas de respiración ...,¿Has notado que has tenido menos conflictos co...,CQ
2,"Hace dos semanas que dejé de fumar, y aunque a...",¿Cómo has manejado las ganas de fumar desde qu...,OQ
3,"Hace dos semanas que dejé de fumar, y aunque a...",¿Has tenido algún momento en el que hayas sent...,CQ
4,"He estado pensando en dejar de fumar, pero es ...",¿Qué estrategias has usado antes para manejar ...,OQ

In [7]:
df_quest.shape

(200, 3)

In [8]:
df_quest['behavior_code_1'].value_counts()

behavior_code_1
OQ    100
CQ    100
Name: count, dtype: int64

## Reflex dataframe:

In [9]:
df_reflex.head()

,client_utterance,clinician_utterance,behavior_code_1
0,He empezado a seguir una rutina de sueño más r...,Parece que estás encontrando el coraje para pr...,CR
1,No puedo cumplir con las visitas de mi supervi...,No puedes cumplir con las visitas de tu superv...,SR
2,He estado cumpliendo con todas las citas de mi...,Entiendo que has cumplido con todas las citas ...,SR
3,"No necesito seguir un horario para dormir, est...",Estás siendo defensivo para evitar reconocer q...,CR
4,No hago nada más que sentarme en casa todo el ...,Sientes que no haces nada más que sentarte en ...,SR

In [10]:
df_reflex['behavior_code_1'].value_counts()

behavior_code_1
SR    102
CR     98
Name: count, dtype: int64

In [11]:
df_reflex.shape

(200, 3)